/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_jasonderas;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jason
 */
public class Clase_Royale extends javax.swing.JFrame {

    /**
     * Creates new form Clase_Royale
     */
    public Clase_Royale() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Login = new javax.swing.JDialog();
        bt_Login = new javax.swing.JButton();
        jl_NUsuraio = new javax.swing.JLabel();
        jl_Contaseña = new javax.swing.JLabel();
        pf_Contraseña = new javax.swing.JPasswordField();
        tf_nUsuario = new javax.swing.JTextField();
        jd_Creacion_Usuario = new javax.swing.JDialog();
        jl_Nombre = new javax.swing.JLabel();
        jl_Apellido = new javax.swing.JLabel();
        jl_nUsuario = new javax.swing.JLabel();
        jl_Contraseña = new javax.swing.JLabel();
        jl_Fecha = new javax.swing.JLabel();
        bt_Creacio_U = new javax.swing.JButton();
        jd_Fecha_nace = new com.toedter.calendar.JDateChooser();
        tf_Nombre = new javax.swing.JTextField();
        tf_Apellido = new javax.swing.JTextField();
        tf_NUsuario1 = new javax.swing.JTextField();
        pf_Contraseña1 = new javax.swing.JPasswordField();
        bt_Color = new javax.swing.JButton();
        jd_Cartas = new javax.swing.JDialog();
        bt_Agrega_Mazo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_Opciones_c = new javax.swing.JTextArea();
        jl_Opcion_de_carta = new javax.swing.JLabel();
        tf_OpcionC = new javax.swing.JTextField();
        jd_Mazos = new javax.swing.JDialog();
        jl_Mazos = new javax.swing.JLabel();
        cb_Mazos = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        j_Mazos = new javax.swing.JTree();
        jd_Union = new javax.swing.JDialog();
        jl_Nombre1 = new javax.swing.JLabel();
        bt_Unirse = new javax.swing.JButton();
        tf_Clan = new javax.swing.JTextField();
        jd_Creacion_U = new javax.swing.JDialog();
        jl_Nombre2 = new javax.swing.JLabel();
        jl_Fecha_Cre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_NC = new javax.swing.JTextField();
        tf_Tipo = new javax.swing.JTextField();
        jd_NC = new com.toedter.calendar.JDateChooser();
        bt_Crear = new javax.swing.JButton();
        jmb_Usuarios = new javax.swing.JMenuBar();
        jm_Usuario = new javax.swing.JMenu();
        jmi_Creacion = new javax.swing.JMenuItem();
        jm_Login = new javax.swing.JMenu();
        jmi_Mazos = new javax.swing.JMenuItem();
        jmi_Cartas = new javax.swing.JMenuItem();
        jm_Clan = new javax.swing.JMenu();
        jmi_CreacionC = new javax.swing.JMenuItem();
        jmi_UC = new javax.swing.JMenuItem();

        jd_Login.setTitle("Login");

        bt_Login.setText("Login");
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
        });

        jl_NUsuraio.setText("Nombre de Usuario");

        jl_Contaseña.setText("Contraseña");

        javax.swing.GroupLayout jd_LoginLayout = new javax.swing.GroupLayout(jd_Login.getContentPane());
        jd_Login.getContentPane().setLayout(jd_LoginLayout);
        jd_LoginLayout.setHorizontalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_LoginLayout.createSequentialGroup()
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(bt_Login))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Contaseña)
                        .addGap(57, 57, 57)
                        .addComponent(pf_Contraseña))
                    .addGroup(jd_LoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_NUsuraio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_nUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jd_LoginLayout.setVerticalGroup(
            jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_LoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_NUsuraio)
                    .addComponent(tf_nUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contaseña)
                    .addComponent(pf_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(bt_Login)
                .addGap(88, 88, 88))
        );

        jd_Creacion_Usuario.setTitle("Creacion de usuario nuevo");

        jl_Nombre.setText("Nombre");

        jl_Apellido.setText("Apellido");

        jl_nUsuario.setText("Nombre de Usuario");

        jl_Contraseña.setText("Contraseña");

        jl_Fecha.setText("Fecha de Nacimiento");

        bt_Creacio_U.setText("Creacion");

        bt_Color.setText("Color Favorito");
        bt_Color.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ColorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_Creacion_UsuarioLayout = new javax.swing.GroupLayout(jd_Creacion_Usuario.getContentPane());
        jd_Creacion_Usuario.getContentPane().setLayout(jd_Creacion_UsuarioLayout);
        jd_Creacion_UsuarioLayout.setHorizontalGroup(
            jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jl_nUsuario)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_NUsuario1))
                                .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jl_Nombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_Nombre))
                                .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jl_Contraseña)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pf_Contraseña1))
                                .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                                    .addComponent(jl_Apellido)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_Apellido)))
                            .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                                .addComponent(jl_Fecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_Creacio_U)
                                    .addComponent(jd_Fecha_nace, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bt_Color)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jd_Creacion_UsuarioLayout.setVerticalGroup(
            jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre)
                    .addComponent(tf_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Apellido)
                    .addComponent(tf_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nUsuario)
                    .addComponent(tf_NUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contraseña)
                    .addComponent(pf_Contraseña1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jd_Creacion_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jd_Fecha_nace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_Color)
                .addGap(24, 24, 24)
                .addComponent(bt_Creacio_U)
                .addGap(21, 21, 21))
        );

        jd_Cartas.setTitle("Agregar una Carta al Mazo");

        bt_Agrega_Mazo.setText("Agregar a un Mazo");
        bt_Agrega_Mazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_Agrega_MazoActionPerformed(evt);
            }
        });

        ta_Opciones_c.setEditable(false);
        ta_Opciones_c.setColumns(20);
        ta_Opciones_c.setRows(5);
        ta_Opciones_c.setText("1. Minipekka\n2. Montapuerco\n3. Golem\n4. Leñador\n5. Dragon Infernal\n6. Dragon\n7. Gigante Noble\n8. Pandilla de Duendes\n");
        jScrollPane1.setViewportView(ta_Opciones_c);

        jl_Opcion_de_carta.setText("Ingrese una opcion");

        javax.swing.GroupLayout jd_CartasLayout = new javax.swing.GroupLayout(jd_Cartas.getContentPane());
        jd_Cartas.getContentPane().setLayout(jd_CartasLayout);
        jd_CartasLayout.setHorizontalGroup(
            jd_CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CartasLayout.createSequentialGroup()
                .addGroup(jd_CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_CartasLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(bt_Agrega_Mazo))
                    .addGroup(jd_CartasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CartasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Opcion_de_carta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_OpcionC)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jd_CartasLayout.setVerticalGroup(
            jd_CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CartasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jd_CartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Opcion_de_carta)
                    .addComponent(tf_OpcionC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(bt_Agrega_Mazo)
                .addGap(44, 44, 44))
        );

        jl_Mazos.setText("Mazos");

        cb_Mazos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cb_Mazos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_MazosItemStateChanged(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Mazos");
        j_Mazos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(j_Mazos);

        javax.swing.GroupLayout jd_MazosLayout = new javax.swing.GroupLayout(jd_Mazos.getContentPane());
        jd_Mazos.getContentPane().setLayout(jd_MazosLayout);
        jd_MazosLayout.setHorizontalGroup(
            jd_MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MazosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(jd_MazosLayout.createSequentialGroup()
                        .addComponent(jl_Mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Mazos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jd_MazosLayout.setVerticalGroup(
            jd_MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_MazosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_MazosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Mazos)
                    .addComponent(cb_Mazos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jl_Nombre1.setText("Nombre del clan");

        bt_Unirse.setText("Unirse");
        bt_Unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UnirseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_UnionLayout = new javax.swing.GroupLayout(jd_Union.getContentPane());
        jd_Union.getContentPane().setLayout(jd_UnionLayout);
        jd_UnionLayout.setHorizontalGroup(
            jd_UnionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UnionLayout.createSequentialGroup()
                .addGroup(jd_UnionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_UnionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jl_Nombre1)
                        .addGap(18, 18, 18)
                        .addComponent(tf_Clan, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_UnionLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(bt_Unirse)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jd_UnionLayout.setVerticalGroup(
            jd_UnionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UnionLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jd_UnionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre1)
                    .addComponent(tf_Clan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(bt_Unirse)
                .addGap(81, 81, 81))
        );

        jl_Nombre2.setText("Nombre del clan");

        jl_Fecha_Cre.setText("Fecha de Creacion");

        jLabel4.setText("Tipo");

        bt_Crear.setText("Crear");
        bt_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_Creacion_ULayout = new javax.swing.GroupLayout(jd_Creacion_U.getContentPane());
        jd_Creacion_U.getContentPane().setLayout(jd_Creacion_ULayout);
        jd_Creacion_ULayout.setHorizontalGroup(
            jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_ULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_Creacion_ULayout.createSequentialGroup()
                        .addComponent(jl_Nombre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_NC))
                    .addGroup(jd_Creacion_ULayout.createSequentialGroup()
                        .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_Fecha_Cre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Crear)
                            .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jd_NC, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                .addComponent(tf_Tipo)))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jd_Creacion_ULayout.setVerticalGroup(
            jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_Creacion_ULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Nombre2)
                    .addComponent(tf_NC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_Fecha_Cre)
                    .addComponent(jd_NC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jd_Creacion_ULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(bt_Crear)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clash Royale");

        jm_Usuario.setText("Usuario");
        jm_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_UsuarioActionPerformed(evt);
            }
        });

        jmi_Creacion.setText("Creacion de Usuario");
        jmi_Creacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CreacionActionPerformed(evt);
            }
        });
        jm_Usuario.add(jmi_Creacion);

        jm_Login.setText("Login");
        jm_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jm_LoginActionPerformed(evt);
            }
        });

        jmi_Mazos.setText("Mazos");
        jmi_Mazos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_MazosActionPerformed(evt);
            }
        });
        jm_Login.add(jmi_Mazos);

        jmi_Cartas.setText("Cartas");
        jmi_Cartas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CartasActionPerformed(evt);
            }
        });
        jm_Login.add(jmi_Cartas);

        jm_Usuario.add(jm_Login);

        jmb_Usuarios.add(jm_Usuario);

        jm_Clan.setText("Clanes");

        jmi_CreacionC.setText("Crear un clan");
        jmi_CreacionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_CreacionCActionPerformed(evt);
            }
        });
        jm_Clan.add(jmi_CreacionC);

        jmi_UC.setText("Unirse a un clan");
        jmi_UC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_UCActionPerformed(evt);
            }
        });
        jm_Clan.add(jmi_UC);

        jmb_Usuarios.add(jm_Clan);

        setJMenuBar(jmb_Usuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jm_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jm_UsuarioActionPerformed

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        if (tf_nUsuario.getText().equalsIgnoreCase(((Usuarios) usuario.get(cont)).getN_usuario()) && pf_Contraseña.getText().equalsIgnoreCase(((Usuarios) usuario.get(cont)).getContraseña())) {
            jmi_Mazos.setEnabled(true);
            jmi_Mazos.setEnabled(true);
            tf_nUsuario.setText("");
            pf_Contraseña.setText("");
            jd_Login.setVisible(false);
            cont++;
        }
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void bt_ColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ColorMouseClicked
        // TODO add your handling code here:
        c = JColorChooser.showDialog(this, "Selecione un color", Color.yellow);
    }//GEN-LAST:event_bt_ColorMouseClicked

    private void jmi_CreacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CreacionActionPerformed
        // TODO add your handling code here:
        jd_Creacion_Usuario.setModal(true);
        jd_Creacion_Usuario.pack();
        jd_Creacion_Usuario.setLocationRelativeTo(this);
        jd_Creacion_Usuario.setVisible(true);
        int edad = 0;
        try {
            edad = (int) (((new Date()).getTime()) - jd_Fecha_nace.getDate().getTime() / (1000 * 60 * 60 * 24));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error y no se crreo el usuario");
        }
        Usuarios us = new Usuarios(pf_Contraseña1.getText(), tf_Nombre.getText(), tf_Apellido.getText(), tf_NUsuario1.getText(), edad, c, jd_Fecha_nace.getDate());
        usuario.add(us);
        tf_Apellido.setText("");
        tf_NUsuario1.setText("");
        tf_Nombre.setText("");
        pf_Contraseña1.setText("");
        jd_Fecha_nace.setDate(new Date());
    }//GEN-LAST:event_jmi_CreacionActionPerformed

    private void jm_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jm_LoginActionPerformed
        // TODO add your handling code here:
        if (usuario.size() < 0) {
            JOptionPane.showMessageDialog(this, "Ocupa crear un usuario primero");
        } else {
            jd_Login.setModal(true);
            jd_Login.pack();
            jd_Login.setLocationRelativeTo(this);
            jd_Login.setVisible(true);
        }
    }//GEN-LAST:event_jm_LoginActionPerformed

    private void jmi_CartasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CartasActionPerformed
        // TODO add your handling code here:
        jd_Cartas.setModal(true);
        jd_Cartas.pack();
        jd_Cartas.setLocationRelativeTo(this);
        jd_Cartas.setVisible(true);
    }//GEN-LAST:event_jmi_CartasActionPerformed

    private void jmi_MazosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_MazosActionPerformed
        // TODO add your handling code here:
        jd_Mazos.setModal(true);
        jd_Mazos.pack();
        jd_Mazos.setLocationRelativeTo(this);
        jd_Mazos.setVisible(true);
    }//GEN-LAST:event_jmi_MazosActionPerformed

    private void bt_Agrega_MazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_Agrega_MazoActionPerformed
        // TODO add your handling code here:
        int tcost = 0;
        int cant = 0;
        int cant2 = 0;
        int op;
        String nombre = "";
        double daño = 0;
        double vida = 0;
        String objetivo = "";
        String velocidad = "";
        int coste = 0;
        String tipo = "";
        op = Integer.parseInt(tf_OpcionC.getText());
        if (op == 1 || tf_OpcionC.getText().equalsIgnoreCase("minipekka")) {
            nombre = "Minipekka";
            daño = 100;
            vida = 200;
            objetivo = "Objetivos Terrestes";
            velocidad = "Alta";
            coste = 4;
            tipo = "Especial";
        } else if (op == 2 || tf_OpcionC.getText().equalsIgnoreCase("montapuerco")) {
            nombre = "Montapuerco";
            daño = 100;
            vida = 200;
            objetivo = "Objetivos Terrestes";
            velocidad = "Alta";
            coste = 4;
            tipo = "Especial";
        } else if (op == 3 || tf_OpcionC.getText().equalsIgnoreCase("golem")) {
            nombre = "Golem";
            daño = 100;
            vida = 800;
            objetivo = "Objetivos Terrestes";
            velocidad = "Baja";
            coste = 8;
            tipo = "Epica";
        } else if (op == 4 || tf_OpcionC.getText().equalsIgnoreCase("leñador")) {
            nombre = "Leñador";
            daño = 200;
            vida = 200;
            objetivo = "Objetivos Terrestes";
            velocidad = "Alta";
            coste = 4;
            tipo = "Legendario";
        } else if (op == 5 || tf_OpcionC.getText().equalsIgnoreCase("dragon infernal")) {
            nombre = "Dragon Infernal";
            daño = 100;
            vida = 300;
            objetivo = "Objetivos Terrestes y Aereos";
            velocidad = "Media";
            coste = 4;
            tipo = "Legendario";
        } else if (op == 6 || tf_OpcionC.getText().equalsIgnoreCase("dragon")) {
            nombre = "Dragon";
            daño = 100;
            vida = 200;
            objetivo = "Objetivos Terrestes y Aereos";
            velocidad = "Media";
            coste = 4;
            tipo = "Epica";
        } else if (op == 7 || tf_OpcionC.getText().equalsIgnoreCase("gigante noble")) {
            nombre = "Gigante noble";
            daño = 100;
            vida = 800;
            objetivo = "Objetivos Terrestes";
            velocidad = "Media";
            coste = 6;
            tipo = "Comun";
        } else if (op == 8 || tf_OpcionC.getText().equalsIgnoreCase("pandilla de duendes")) {
            nombre = "Pandilla de Duendes";
            daño = 100;
            vida = 100;
            objetivo = "Objetivos Terrestes y Aereos";
            velocidad = "Alta";
            coste = 3;
            tipo = "Comun";
        } else {
            JOptionPane.showMessageDialog(this, "Opcion de carta no valida");
        }
        if (cant == 3) {
            JOptionPane.showMessageDialog(this, "Ya Hay tres cartas en ese maso");
        } else {
            s = new Carta(nombre, daño, vida, objetivo, velocidad, coste, tipo);
            tcost += coste;
            cartas.add(s);
            mazos.setCoste(coste);
            mazos.setCartas(cartas);
            ArrayList m = new ArrayList();
            m.add(mazos);
            ((Usuarios) usuario.get(cont)).setMazos1(m);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_Mazos.getModel();
            modelo.addElement(m);
            if (((Usuarios) usuario.get(cont)).getMazos1().size() == 2) {
                JOptionPane.showMessageDialog(this, "Mazo uno llenado");
                tcost = 0;
                cant2++;
            } else if (((Usuarios) usuario.get(cont)).getMazos2().size() == 2) {
                JOptionPane.showMessageDialog(this, "Mazo dos llenado");
                tcost = 0;
                cant2++;
            } else if (((Usuarios) usuario.get(cont)).getMazos3().size() == 2) {
                JOptionPane.showMessageDialog(this, "Mazo tres llenado");
                tcost = 0;
                cant2++;
            }
            if (cant2 == 3) {
                JOptionPane.showMessageDialog(this, "No hay mas Mazos Disponibles");
            }
            cont++;
        }
    }//GEN-LAST:event_bt_Agrega_MazoActionPerformed

    private void cb_MazosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_MazosItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {

        }
    }//GEN-LAST:event_cb_MazosItemStateChanged

    private void jmi_UCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_UCActionPerformed
        // TODO add your handling code here:
        jd_Union.setModal(true);
        jd_Union.pack();
        jd_Union.setLocationRelativeTo(this);
        jd_Union.setVisible(true);
    }//GEN-LAST:event_jmi_UCActionPerformed

    private void bt_UnirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UnirseActionPerformed
        // TODO add your handling code here:

        if (((Clanes) clanes.get(cont)).getNombre().equalsIgnoreCase(tf_Clan.getText())) {
            JOptionPane.showMessageDialog(this, "Se unio corectamente");
        }
    }//GEN-LAST:event_bt_UnirseActionPerformed

    private void jmi_CreacionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_CreacionCActionPerformed
        // TODO add your handling code here:
        jd_Creacion_U.setModal(true);
        jd_Creacion_U.pack();
        jd_Creacion_U.setLocationRelativeTo(this);
        jd_Creacion_U.setVisible(true);
    }//GEN-LAST:event_jmi_CreacionCActionPerformed

    private void bt_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearActionPerformed
        // TODO add your handling code here:
        if (tf_Tipo.getText().equalsIgnoreCase("bronce") || tf_Tipo.getText().equalsIgnoreCase("palta") || tf_Tipo.getText().equalsIgnoreCase("oro") || tf_Tipo.getText().equalsIgnoreCase("legendario")) {
            clanes.add(new Clanes(tf_NC.getText(), jd_NC.getDate(), "", tf_Tipo.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "Tipo de clan no validao");
        }
    }//GEN-LAST:event_bt_CrearActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clase_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clase_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clase_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clase_Royale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clase_Royale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Agrega_Mazo;
    private javax.swing.JButton bt_Color;
    private javax.swing.JButton bt_Creacio_U;
    private javax.swing.JButton bt_Crear;
    private javax.swing.JButton bt_Login;
    private javax.swing.JButton bt_Unirse;
    private javax.swing.JComboBox<String> cb_Mazos;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree j_Mazos;
    private javax.swing.JDialog jd_Cartas;
    private javax.swing.JDialog jd_Creacion_U;
    private javax.swing.JDialog jd_Creacion_Usuario;
    private com.toedter.calendar.JDateChooser jd_Fecha_nace;
    private javax.swing.JDialog jd_Login;
    private javax.swing.JDialog jd_Mazos;
    private com.toedter.calendar.JDateChooser jd_NC;
    private javax.swing.JDialog jd_Union;
    private javax.swing.JLabel jl_Apellido;
    private javax.swing.JLabel jl_Contaseña;
    private javax.swing.JLabel jl_Contraseña;
    private javax.swing.JLabel jl_Fecha;
    private javax.swing.JLabel jl_Fecha_Cre;
    private javax.swing.JLabel jl_Mazos;
    private javax.swing.JLabel jl_NUsuraio;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Nombre1;
    private javax.swing.JLabel jl_Nombre2;
    private javax.swing.JLabel jl_Opcion_de_carta;
    private javax.swing.JLabel jl_nUsuario;
    private javax.swing.JMenu jm_Clan;
    private javax.swing.JMenu jm_Login;
    private javax.swing.JMenu jm_Usuario;
    private javax.swing.JMenuBar jmb_Usuarios;
    private javax.swing.JMenuItem jmi_Cartas;
    private javax.swing.JMenuItem jmi_Creacion;
    private javax.swing.JMenuItem jmi_CreacionC;
    private javax.swing.JMenuItem jmi_Mazos;
    private javax.swing.JMenuItem jmi_UC;
    private javax.swing.JPasswordField pf_Contraseña;
    private javax.swing.JPasswordField pf_Contraseña1;
    private javax.swing.JTextArea ta_Opciones_c;
    private javax.swing.JTextField tf_Apellido;
    private javax.swing.JTextField tf_Clan;
    private javax.swing.JTextField tf_NC;
    private javax.swing.JTextField tf_NUsuario1;
    private javax.swing.JTextField tf_Nombre;
    private javax.swing.JTextField tf_OpcionC;
    private javax.swing.JTextField tf_Tipo;
    private javax.swing.JTextField tf_nUsuario;
    // End of variables declaration//GEN-END:variables
private ArrayList<Usuarios> usuario = new ArrayList();
    private int cont = 0;
    private Color c;
    private Carta s;
    private Mazo mazos;
    private ArrayList<Carta> cartas = new ArrayList();
    private ArrayList clanes = new ArrayList();
}
